-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
vim.loader.enable()
local autocmd = vim.api.nvim_create_autocmd
local g = vim.g
local version = vim.version
_G["mnw?"] = (_G.mnw ~= nil)
do
  local builtins = {"gzip", "zip", "zipPlugin", "tar", "tarPlugin", "getscript", "getscriptPlugin", "vimball", "vimballPlugin", "2html_plugin", "logipat", "rrhelper", "spellfile_plugin", "matchit"}
  for _, plugin in ipairs(builtins) do
    g[("loaded_" .. plugin)] = 1
  end
end
do
  local providers = {"python3", "node", "ruby", "perl"}
  for _, provider in ipairs(providers) do
    g[("loaded_" .. provider .. "_provider")] = 0
  end
end
if not _G["mnw?"] then
  local function build_parinfer(_1_)
    local kind = _1_.kind
    local path = _1_.path
    local _arg_2_ = _1_.spec
    local name = _arg_2_.name
    if ((name == "parinfer-rust") and ((kind == "update") or (kind == "install"))) then
      local function _3_()
      end
      return vim.system({"cargo", "build", "--release"}, {cwd = path}, _3_)
    else
      return nil
    end
  end
  local function build_hooks(_5_)
    local data = _5_.data
    return build_parinfer(data)
  end
  autocmd("PackChanged", {desc = "build plugins", callback = build_hooks})
  vim.pack.add({{src = "https://github.com/rktjmp/hotpot.nvim", version = version.range("^2.0.0")}})
  require("hotpot")
else
end
require("startup")
require("core")
if g.neovide then
  require("neovide")
else
end
require("ui")
require("editor")
require("navigation")
require("lsp")
require("code")
return require("highlights")