-- @generated by hotpot.nvim using fennel 1.6.1, edits to this file may be lost
local g = vim.g
local version = vim.version
local pack = vim.pack
vim.loader.enable()
do
  local builtins = {"gzip", "zip", "zipPlugin", "tar", "tarPlugin", "getscript", "getscriptPlugin", "vimball", "vimballPlugin", "2html_plugin", "logipat", "rrhelper", "spellfile_plugin", "matchit"}
  for _, plugin in ipairs(builtins) do
    g[("loaded_" .. plugin)] = 1
  end
end
pack.add({{src = "https://github.com/rktjmp/hotpot.nvim", version = version.range("^2.0.0")}})
require("hotpot")
require("core")
if g.neovide then
  require("neovide")
else
end
require("build-hooks")
require("startup")
require("ui")
require("editor")
require("navigation")
require("lsp")
require("code")
return require("highlights")